FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ARG FIREBASE_API_KEY
ARG FIREBASE_APP_ID
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_DATABASE_URL
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_STORAGE_BUCKET

ENV FIREBASE_API_KEY=$FIREBASE_API_KEY
ENV FIREBASE_APP_ID=$FIREBASE_APP_ID
ENV FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
ENV FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET

RUN npm run build


FROM node:18-alpine as run

WORKDIR /app

COPY --from=build /app/.output .

CMD ["node", "server/index.mjs"]
